apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-produktside-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 3000
  liveness:
    path: /dagpenger/api/isalive
  readiness:
    path: /dagpenger/api/isready
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: cdn.nav.no
        - host: g.nav.no
        - host: api.sanity.io
        - host: apicdn.sanity.io
        - host: cdn.sanity.io
        - host: rt6o382n.api.sanity.io
        - host: rt6o382n.apicdn.sanity.io
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/pki/tls/certs/ca-bundle.crt"
    - name: DEKORATOR_MILJO
      value: "{{dekoratorMiljo}}"
    - name: NPM_CONFIG_CACHE
      value: /tmp
    - name: NEXT_PUBLIC_SANITY_DATASETT
      value: "{{sanityDatasett}}"
  envFrom:
    - secret: dp-produktside-frontend-sanity-cms-read-token
  {{ingresses}}
